baseURL = "https://shusio.com/"
footnoteReturnLinkContents = "↩"
languageCode = "ja-JP"
title = "Shusio のメモ"
publishDir = "docs"
theme = "jeffprod"

[params]
    AuthorName = "shusio"
    GitHubUser = "4XSA5yltIDO0Hcuw"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
